#!/usr/bin/env python3
"""
Collatz Sequence Data Plotter

Reads CSV data generated by collatz_data_generator.cpp and creates a plot.
Requires: matplotlib and pandas

Install: pip install matplotlib pandas
Run:     python3 plot_collatz.py
         python3 plot_collatz.py collatz_data.csv
         python3 plot_collatz.py collatz_data.csv -o my_plot.png
         python3 plot_collatz.py -o collatz_plot.png   # save without displaying
         python3 plot_collatz.py --no-show -o plot.png # headless save

Arguments:
  input            CSV file to read (default: collatz_data.csv)
  -o, --output     Save the plot to this file (e.g. plot.png, plot.pdf).
                   When omitted the plot is displayed interactively.
  --no-show        Do not open an interactive window (useful in headless
                   environments). Requires --output / -o to be set so that
                   the plot is still captured somewhere.
"""

import sys

# Set the backend before pyplot is imported so that --no-show works
# correctly even when matplotlib has already been initialised.
import matplotlib
if '--no-show' in sys.argv:
    matplotlib.use('Agg')

import matplotlib.pyplot as plt  # noqa: E402 (must follow backend setup)
import pandas as pd
import argparse


def plot_collatz_data(filename='collatz_data.csv', output=None, show=True):
    """Read and plot Collatz sequence max values.

    Parameters
    ----------
    filename : str
        Path to the CSV file produced by collatz_data_generator.cpp.
    output : str or None
        If provided, the plot is saved to this path (format is inferred from
        the file extension, e.g. ``.png``, ``.pdf``, ``.svg``).
    show : bool
        When *True* (default) the plot is displayed in an interactive window.
        Pass *False* to suppress the window (useful in headless/CI environments).
    """

    try:
        # Read CSV file
        data = pd.read_csv(filename)

        # Create figure
        plt.figure(figsize=(12, 6))

        # Plot the data
        plt.plot(data['index'], data['max_value'], 'b-', linewidth=1, alpha=0.7)
        plt.scatter(data['index'], data['max_value'], c='red', s=10, alpha=0.5)

        # Labels and title
        plt.xlabel('Iteration Index', fontsize=12)
        plt.ylabel('Maximum Value in Sequence', fontsize=12)
        plt.title('Collatz (3n+1)+1 Sequence - Maximum Values', fontsize=14, fontweight='bold')

        # Grid
        plt.grid(True, alpha=0.3)

        # Use logarithmic scale if values span multiple orders of magnitude
        if data['max_value'].max() / data['max_value'].min() > 100:
            plt.yscale('log')
            plt.ylabel('Maximum Value in Sequence (log scale)', fontsize=12)

        # Tight layout
        plt.tight_layout()

        # Save plot to disk if an output path was requested
        if output:
            plt.savefig(output, dpi=150, bbox_inches='tight')
            print(f"Plot saved to: {output}")

        # Show plot interactively (may be suppressed in headless environments)
        if show:
            plt.show()

        plt.close()

        # Print statistics
        print("\n" + "="*50)
        print("Statistics:")
        print("="*50)
        print(f"Total iterations: {len(data)}")
        print(f"Min max value: {data['max_value'].min()}")
        print(f"Max max value: {data['max_value'].max()}")
        print(f"Mean max value: {data['max_value'].mean():.2f}")
        print(f"Median max value: {data['max_value'].median():.2f}")
        print("="*50)

    except FileNotFoundError:
        print(f"Error: File '{filename}' not found!")
        print("Please run collatz_data_generator first to generate the data.")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Plot Collatz sequence max values from a CSV file."
    )
    parser.add_argument(
        "input",
        nargs="?",
        default="collatz_data.csv",
        help="CSV file generated by collatz_data_generator (default: collatz_data.csv)",
    )
    parser.add_argument(
        "-o", "--output",
        default=None,
        metavar="FILE",
        help="Save the plot to FILE (e.g. collatz_plot.png). "
             "Format is determined by the file extension.",
    )
    parser.add_argument(
        "--no-show",
        action="store_true",
        help="Do not open an interactive display window. "
             "Must be used together with --output so the plot is captured.",
    )
    args = parser.parse_args()

    if args.no_show and not args.output:
        parser.error("--no-show requires --output / -o so the plot is saved somewhere.")

    print(f"Loading data from: {args.input}")
    plot_collatz_data(
        filename=args.input,
        output=args.output,
        show=not args.no_show,
    )
